# Generated by Django 5.2 on 2025-10-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educational_background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Field_of_studey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phonenumber', models.IntegerField(blank=True, null=True)),
                ('GPA', models.IntegerField(blank=True, null=True)),
                ('school', models.TextField(blank=True, null=True)),
                ('national_code', models.IntegerField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now=True, null=True)),
                ('educational_background', models.ManyToManyField(blank=True, null=True, to='Apps.educational_background')),
                ('field_of_studey', models.ManyToManyField(blank=True, null=True, to='Apps.field_of_studey')),
                ('gender', models.ManyToManyField(blank=True, null=True, to='Apps.gender')),
            ],
        ),
    ]
