# Generated by Django 5.2 on 2025-10-10 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_teacher_remove_students_gender_students_teacher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.IntegerField()),
                ('physic', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('hendese', models.IntegerField()),
                ('amar_ehtemal', models.IntegerField()),
                ('persion', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='score',
            field=models.ManyToManyField(blank=True, null=True, to='Apps.score'),
        ),
    ]
