# Generated by Django 5.2 on 2025-10-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0003_score_students_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='score',
        ),
        migrations.AddField(
            model_name='students',
            name='amar_ehtemal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='chemistry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='hendese',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='math',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='persion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='physic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
