# Generated by Django 5.2 on 2025-10-11 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0004_remove_students_score_students_amar_ehtemal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='amar_ehtemal',
        ),
        migrations.RemoveField(
            model_name='students',
            name='chemistry',
        ),
        migrations.RemoveField(
            model_name='students',
            name='hendese',
        ),
        migrations.RemoveField(
            model_name='students',
            name='math',
        ),
        migrations.RemoveField(
            model_name='students',
            name='persion',
        ),
        migrations.RemoveField(
            model_name='students',
            name='physic',
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.IntegerField()),
                ('physic', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('hendese', models.IntegerField()),
                ('persion', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Apps.score'),
        ),
    ]
