# Generated by Django 5.2 on 2025-10-13 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0005_remove_students_amar_ehtemal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Apps.score'),
        ),
    ]
