# Generated by Django 5.2 on 2025-10-15 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0006_alter_students_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='score',
            name='chemistry',
        ),
        migrations.RemoveField(
            model_name='score',
            name='hendese',
        ),
        migrations.RemoveField(
            model_name='score',
            name='math',
        ),
        migrations.RemoveField(
            model_name='score',
            name='persion',
        ),
        migrations.RemoveField(
            model_name='score',
            name='physic',
        ),
        migrations.AddField(
            model_name='score',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='students',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Apps.score'),
        ),
        migrations.AddField(
            model_name='score',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Apps.lesson'),
        ),
    ]
