# Generated by Django 5.2 on 2025-10-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0007_lesson_remove_score_chemistry_remove_score_hendese_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='score',
        ),
        migrations.AddField(
            model_name='students',
            name='score',
            field=models.ManyToManyField(blank=True, null=True, to='Apps.score'),
        ),
    ]
