# Generated by Django 5.2 on 2025-10-16 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0008_remove_students_score_students_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='educational_background',
        ),
        migrations.RemoveField(
            model_name='students',
            name='field_of_studey',
        ),
        migrations.AddField(
            model_name='students',
            name='educational_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Apps.educational_background'),
        ),
        migrations.AddField(
            model_name='students',
            name='field_of_studey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Apps.field_of_studey'),
        ),
    ]
