# Generated by Django 5.2.7 on 2025-11-24 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0010_city_school_remove_lesson_grade_alter_students_gpa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typeteaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Apps.typeteaching'),
        ),
    ]
