# Generated by Django 5.2.7 on 2025-11-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0011_typeteaching_teacher_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='type',
        ),
        migrations.AddField(
            model_name='teacher',
            name='type',
            field=models.ManyToManyField(null=True, to='Apps.typeteaching'),
        ),
    ]
