# Generated by Django 5.2.7 on 2025-11-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0012_remove_teacher_type_teacher_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, to='Apps.typeteaching'),
        ),
    ]
